[build-system]
requires = ["intreehooks", "wheel", "meson"]
build-backend = "intreehooks:loader"

[tool.intreehooks]
build-backend = "mesonpep517.buildapi"

[tool.backend.scripts]
backend = "mesonpep517:main"
